on: [workflow_dispatch]

name: GitHub Actions Ipynb for publishing
jobs:
  ipynb_for_publishing:
    runs-on: ubuntu-latest
    name: Ipynb for publishing
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Skim example file
        id: skim
        uses: c2dh/journal-of-digital-history-ipynb-skim-action@v1.0.0
        with:
          notebook: 'article.ipynb'
          output_notebook: 'skim-article.ipynb'
      # Use the output from the `hello` step
      - name: Use the output
        run: echo "number of cells ${{ steps.skim.outputs.size }} - output ${{ steps.skim.outputs.outputNotebook }}"
      - name: committing changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Automated commit
          branch: skim
          create_branch: true
      
      - name: creating pull request
        run: gh pr create -B ${{ github.ref }} -H skim --title 'Comparison between skim review of the article and the main article' --body 'Created by Github action'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
